### ISSUE TITLE
where to find the following Altera Quartus 9.0 SP2 files

### ISSUE THREAD

**Issue by gfernval** [mx-shift/mini-tray#1]
Wanted to put this request in altera_archiving but can´t:

To the point: do you know where to find any of the files belonging to Altera Quartus II 9.0 SP2?

 90sp2_nios2eds_windows.exe (12708709 bytes)
 90sp2_modelsim_ae_windows.exe (231173223 bytes)
 90sp2_dsp_builder_windows.exe (106965748 bytes)

thanks

**Comment by mx-shift** [comment]
I have the first two.  Unfortunately archive.org is still read-only so I can't upload them currently.  Feel free to email me at rick at mxshift.com and we'll figure something out.
